trigger:
  - development
  - release/*
      
resources:
  repositories:
    - repository: self
    - repository: deployments
      type: git
      name: jm-common-deployments

stages:
- template: helm-chart.yaml@deployments
