apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: build-agents
  labels:
    app: linux-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-agent
  template:
    metadata:
      labels:
        app: linux-agent
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if or .Values.agent.dockerNodes .Values.agent.kaniko.enabled }}
      volumes:
        {{- if .Values.agent.dockerNodes }}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        {{- end }}
        {{- if .Values.agent.kaniko.enabled }}
        - name: kaniko
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-kaniko
        {{- end }}
      {{- end }}
      containers:
      - name: linux-agent
        image: jabbermouth/ads-linux-agent:v1.0.5
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if or .Values.agent.dockerNodes .Values.agent.kaniko.enabled }}
        volumeMounts:
          {{- if .Values.agent.dockerNodes }}
          - mountPath: /var/run/docker.sock
            name: docker-sock
          {{- end }}
          {{- if .Values.agent.kaniko.enabled }}
          - mountPath: /kaniko
            name: kaniko
          {{- end }}
        {{- end }}
        env:
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-pat
                key: pat
          - name: AZP_URL
            value: {{ .Values.agent.organisationUrl }}
          - name: AZP_AGENT_NAME
            value: {{ regexReplaceAll "\\W+" .Release.Name " " | title }}
          - name: AZP_POOL
            value: {{ .Values.agent.pool }}
          - name: AZP_WORK
            value: "_work"
          - name: DEPLOYMENT_NAME
            value: {{ .Release.Name }}
      nodeSelector:
        kubernetes.io/os: linux