{{- if .Values.agent.kaniko.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kaniko
  namespace: build-agents
  labels:
    app: {{ .Release.Name }}-kaniko
spec:
  storageClassName: {{ .Values.agent.kaniko.storageClass }}
  accessModes:
    - {{ .Values.agent.kaniko.accessMode }}
  resources:
    requests:
      storage: {{ .Values.agent.kaniko.size }}
{{- end }}